Feature/exercises categories
adoppp/react-app-team-4 pull request #51
Opened 2023-11-13 16:54 UTC by KRVitalik

2023-11-15 13:35 UTC, adoppp requested changes

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesCategories/ExercisesCategories.jsx
мы не стилизуем navlink мы пишем обычный link  и стилизуем то что внутри него, оборачивам линкой нашу кнопку или в твоей случае как я понял span. обратить к ней лучше будет так:
```
.category__list { 
    //styles for ul

    & li a span {
        //styles for Link content
    }
}
```

сама разметка при этом выглядит вот так: 

```
<ul className={cn('category__list')}>
    <li>
        <Link to='path'>
            <span>
                 Body parts
             </span>
         </Link>
    </li>
    <li>
        <Link to='path'>
            <span>
                 Muscles
             </span>
         </Link>
    </li>
    <li>
        <Link to='path'>
            <span>
                 Equipment
             </span>
         </Link>
    </li>
</ul>
```

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesCategories/ExercisesCategories.module.scss
по поводу стилей выше расписал

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesPage.jsx
> +        <h2>ExercisesPage</h2>
это должен быть компонент Title

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesPage.jsx
> +    <div className={cn('section')}>
это не section, а exercize (блок) exercize__element_modifier

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesPage.jsx
и лучше это вложить в контейнер с классном exercizes__categories, а тот див в котором все сейчас это соновной контейнер, к тому же лучше обернуть эту всю трахамундию в тег section

2023-11-15 13:35 UTC, adoppp commented on src/components/pages/ExercisesPage/ExercisesPage.module.scss
по стилям выше прописано

2023-11-15 15:00 UTC, KRVitalik commented on src/components/pages/ExercisesPage/ExercisesCategories/ExercisesCategories.jsx
я використав NavLink, тому, що він має клас ".active", і я до нього звертаюсь, щоб підсвітити вибрану категорію, а звичайний Link цього класу немає.

2023-11-17 08:08 UTC, adoppp requested changes
обнови менй и смогу принять, пересмотри ещетраз верстку и внеси все правки кроме навлинк, его оставляй. жду

2023-11-17 12:32 UTC, adoppp approved these changes

2023-11-17 12:32 UTC, merged